[package]
name = "cairovm_verifier_fri"
description.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
serde_with.workspace = true
starknet-crypto.workspace = true
starknet-core.workspace = true
thiserror.workspace = true
cairovm_verifier_transcript.workspace = true
sha3.workspace = true
starknet-types-core.workspace = true
cairovm_verifier_air.workspace = true
cairovm_verifier_commitment.workspace = true
